#!/bin/bash
#
# catsub -1 n1 -2 n2 [file1 file2 ...]
#
# Print lines [n1 ... n2] of files, inclusive. 
# Error checking is performed on n1,n2 to ensure:
#	1. n2 >= n1
# 
# If -1 n1 or -2 n2 are unspecified, n1 = 1; n2 = EOF
#
# =================================================
# Author: Michael B Hynes, mbhynes@uwaterloo.ca
# License: GPL 3
# Creation Date: Sun Jan 25 16:21:55 2015
# Last Modified: Mon 14 Dec 2015 03:33:18 PM EST
# =================================================

line1="1"
line2="9999999"

SCRIPT_NAME=$(basename $0)
msg () {
	echo "$SCRIPT_NAME: $@" 1>&2
}
warn () {
	msg WARNING: $@
}
error () {
	msg ERROR: $@
}

optstring="1:2:"
while getopts "$optstring" opt; do
	case "$opt" in
		1)
			line1="$OPTARG" #first line of subsection
			;;
		2)
			line2="$OPTARG" #last line of subsection
			;;
		:)
			error "-$opt requires argument" 
			;; 
		?)
			error invalid option
			;; 
	esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
	disp_opts -n 15 -h $0 2>/dev/null
	exit 1
fi

if [ -z "$line1" ]; then
	line1=1
	warn "using line1=1 for all input files"
fi

if [ -z "$line2" ]; then
	line2=$(wc -l <$1)
	warn "using the length of $1 as last line for all input files: $line2"
fi


for file in "$@"; do
	if [ ! -r "$file" ]; then
		error "$file is not readable or does not exist"
		continue
	fi

	# len=$(wc -l <$file)
	# if ((line2 > len)); then
	# 	warn "line2 > file_len: $line2 > $len; using line2=$len"
	# 	line2=$len
	# fi

	if ((line1 > line2)); then
		warn "line1 > line2: $line1 > $line2: swapping values"
		tmp=$line2
		line2=$line1
		line1=$tmp
	fi

	delta=$((line2 - line1 + 1))
	head -n $line2 $file \
		| tail -n $delta

done

