#!/bin/bash
#
# /home/mbhynes/bin/epsfig2pdf
# =================================================
# Author: Michael B Hynes, mbhynes@uwaterloo.ca
# License: GPL 3
# Creation Date: Tue 28 Jul 2015 10:41:26 PM EDT
# Last Modified: Fri 31 Jul 2015 12:17:44 PM EDT
# =================================================
. latex_header

make_main() { f=$1;
	preamble
	begin_document

	ftype=$(ext $f)
	if [ -z "$ftype" ]; then
		ftype=bash
	fi

	if [[ "$ftype" == .scala ]]; then
		ftype=java
	fi

	if [ ! -f "$f" ]; then
		error "$f is not a valid file!"
	fi
	epstexfigure $f "$caption"
	end_document
}

compile() { f="$1";
	pdflatex "$f"
	pdflatex "$f"
}

SCRIPT_NAME=$(basename $0)
msg () {
	echo "$SCRIPT_NAME: $@" 1>&2
}
warn () {
	msg WARNING: $@
}
error () {
	msg ERROR: $@
}

optstring="t:d"
while getopts "$optstring" opt; do
	case "$opt" in
		t)
			caption="$OPTARG"
			;;
		d)
			dry_run=true
			;;
		:)
			error "-$opt requires argument" 
			;; 
		?)
			error invalid option
			;; 
	esac
done
shift $((OPTIND - 1))

for fin in $@; do
	fout=$(mktemp)
	if [ -n "$dry_run" ]; then
		make_main "$fin"
		continue
	fi
	make_main "$fin" > "$fout".tex
	compile "$fout" 1>&2
	rm "$fout" $(basename $fout).{out,log,aux}

	extension=$(ext $fin)
	base=$(basename $fin $extension)
	msg "Writing code file to $base.pdf"
	mv $(basename $fout).pdf $base.pdf
done
