#!/bin/bash
#
# /home/mbhynes/bin/epsfig2pdf
# =================================================
# Author: Michael B Hynes, mbhynes@uwaterloo.ca
# License: GPL 3
# Creation Date: Tue 28 Jul 2015 10:41:26 PM EDT
# Last Modified: Thu 06 Aug 2015 11:30:15 AM EDT
# =================================================
. latex_header

make_main() { f=$1;
	preamble
	begin_document
	epstexfigure $f "$caption"
	end_document
}

compile() { f="$1";
	msg "compiling $f"
	if [ -n "$VERBOSE" ]; then
		pdflatex "$f" 2>&1
		pdflatex "$f" 2>&1
	else
		pdflatex "$f" 2>&1 >/dev/null
		pdflatex "$f" 2>&1 >/dev/null
	fi
}

SCRIPT_NAME=$(basename $0)
msg () {
	echo "$SCRIPT_NAME: $@" 1>&2
}
warn () {
	msg WARNING: $@
}
error () {
	msg ERROR: $@
}

optstring="t:d"
while getopts "$optstring" opt; do
	case "$opt" in
		t)
			caption="$OPTARG"
			;;
		d)
			dry_run=true
			;;
		:)
			error "-$opt requires argument" 
			;; 
		?)
			error invalid option
			;; 
	esac
done
shift $((OPTIND - 1))

if (($# == 0)); then
	disp_opts -n 10 -h $0 2>/dev/null
	exit 0
fi

for fin in $@; do
	fout=$(basename $(mktemp -d)).tex
	if [ -n "$dry_run" ]; then
		msg "DRY RUN: adding $fin to tex file $fout"
		make_main "$fin"
		continue
	fi
	make_main "$fin" > "$fout"
	compile "$fout"

	extension=$(ext $fin)
	base=$(basename $fin $extension)
	msg "Writing $fout to $base.pdf"
	mv $(basename $fout .tex).pdf $base.pdf
	rm "$fout" $(basename $fout .tex).{out,log,aux}
done
