#!/bin/bash
#
# /home/mbhynes/bin/epsfig2pdf
# =================================================
# Author: Michael B Hynes, mbhynes@uwaterloo.ca
# License: GPL 3
# Creation Date: Tue 28 Jul 2015 10:41:26 PM EDT
# Last Modified: Fri 25 Sep 2015 06:25:42 PM EDT
# =================================================
. latex_header

TEXFLAGS="-file-line-error -interaction nonstopmode -shell-escape"
width=0.9

make_main() { f=$1;
	preamble
	begin_document
	if [ ! -r "$f" ]; then
		error "$f is not a valid file!"
	fi
	epstexfigure $f "$width" "$caption"
	end_document
}

compile() { f="$1";
	msg "compiling $f"
	if [ -n "$VERBOSE" ]; then
		pdflatex "$f" 2>&1
		pdflatex "$f" 2>&1
	else
		pdflatex $TEXFLAGS "$f" 2>&1 >/dev/null
		pdflatex $TEXFLAGS "$f" 2>&1 >/dev/null
	fi
}

SCRIPT_NAME=$(basename $0)
msg () {
	echo "$SCRIPT_NAME: $@" 1>&2
}
warn () {
	msg WARNING: $@
}
error () {
	msg ERROR: $@
}

optstring="w:t:dv"
while getopts "$optstring" opt; do
	case "$opt" in
		w)
			width="$OPTARG"
			;;
		v)
			VERBOSE="TRUE"
			;;
		t)
			caption="$OPTARG"
			;;
		d)
			dry_run=true
			;;
		:)
			error "-$opt requires argument" 
			;; 
		?)
			error invalid option
			;; 
	esac
done
shift $((OPTIND - 1))

if (($# == 0)); then
	disp_opts -n 10 -h $0 2>/dev/null
	exit 0
fi

for fin in $@; do
	fdir=$(dirname $fin)
	msg "Processing $fin"
	extension=$(ext $fin)
	base=$(basename $fin $extension)

	# delete the converted eps-pdf file, if it exists
	fpdf="$base-eps-converted-to.pdf"
	if [ -f "$fpdf" ]; then
		msg "Deleting existent $fpdf"
		rm "$fpdf"
	fi
	fpdf="$base.pdf"
	if [ -f "$fpdf" ]; then
		msg "Deleting existent $fpdf"
		rm "$fpdf"
	fi

	fout=$(basename $(mktemp -d)).tex
	if [ -n "$dry_run" ]; then
		msg "DRY RUN: adding $fin to tex file $fout"
		make_main "$fin"
		continue
	fi
	make_main "$fin" > "$fout"
	compile "$fout"

	msg "Writing $fout to $orig_dir$base.pdf"
	mv $(basename $fout .tex).pdf $base.pdf
	rm "$fout" $(basename $fout .tex).{out,log,aux}

done
