#!/bin/bash
#
# ext [file1 file2 ...]
#
# Print the file extension of input files.
#
# The extension is taken as the suffix of the rightmost
# substring beginning with a period, '.'
#
# >> ext test.png test.png.old .rc test
# .png
# .old
# .rc
# <nullstring>
#
# Creation Date: Tue 15 Oct 2013 05:12:54 PM EDT
# Last Modified: Sun 25 Jan 2015 08:45:03 PM EST
#===================================================

#!/bin/bash

# print file extensions
if (( $# == 0 ))
then
	disp_opts -h -n 20 $0 2>/dev/null
	# echo "usage: ext.sh <f1.ext1> ... <fn.extn>"
	# echo ">>.ext1 .ext2 .ext3"
	exit 1
fi
while (( $# > 0))
do
	s=$1
	n=${#s}
	i=-1
	while [ "${s: $i:1}" != '.' ] && ((n+i >= 0))
	do
		((i--))
	done
	if ((n+i >= 0))
	then
		echo ${s: $i}
	else
		echo
	fi
	shift
done
exit 0
