#!/bin/bash
#
# lsown [dir1 dir2 ...]
#
# List files belonging to $USER in the given directories
# This script is slow and dumb. It's just to supprss warning
# messages when deleting files from /tmp on a shared env.

if [ "$#" -eq 0 ]; then
	DIRS="$PWD"
else
	DIRS="$@"
fi

print_file_owner()
{
	file="$1"
	ls -oad "$file" \
		| cut -d " " -f3
}

ls_user_files() # -dir
{
	dir=$1
	IFS=$'\n'
	delim=' '
	for file in $(ls $dir/); do
		if grep -q "$USER" <<< $(print_file_owner $dir/$file); then
			echo "$dir/$file"
		fi
	done
}

for d in $DIRS; do
	if [ -d "$d" ]; then
		ls_user_files "$d"
	fi
done

exit 0
