#!/bin/bash
#
# lsown [-u <user>] [-v] [dir1 dir2 ...]
#
# List files belonging to <user> in the given directories, ($USER by default)
# Passing the -v (inversion) flag lists the files not belonging to <user>
# ==========================================================================

SCRIPT_NAME=$(basename $0)
msg () {
	echo "$SCRIPT_NAME: $@" 1>&2
}
warn () {
	msg WARNING: $@
}
error () {
	msg ERROR: $@
}

printfiles() {
	path="$@"
	ls -oad "$path"/* \
		| grep $invert_flag "$username" \
		| sed -r -e 's/.* (\/.*)/\1/'
}

optstring="pu:hv"
while getopts "$optstring" opt; do
	case "$opt" in
		p)
			ignore_pids="true"
			;;
		u)
			username="${OPTARG/\\/\\\\\\}"
			;;
		h)
			disp_opts -h $0 2>/dev/null
			exit 0
			;;
		v)
			invert_flag="-v"
			;;
		:)
			error "-$opt requires argument" 
			;; 
		?)
			error invalid option
			;; 
	esac
done
shift $((OPTIND - 1))

if [ "$#" -eq 0 ]; then
	DIRS="$PWD"
else
	DIRS="$@"
fi

# escape HIMROD-DOMAIN\ slashes
if [ -z "$username" ]; then
	username=${USER/\\/\\\\\\}
fi

for d in $DIRS; do
	if [ -d "$d" ]; then
		if [ -n "$ignore_pids" ]; then
			printfiles $d | grep -v '.*\.pid'
		else
			printfiles $d
		fi
	fi
done

exit 0
