#!/bin/bash
# list the owner of files

if [ "$#" -eq 0 ]; then
	DIRS="$PWD"
else
	DIRS="$@"
fi

ls_user_files() # -dir
{
	IFS=$'\n'
	delim=' '
	for file in $(ls $1/); do
		if grep -q "$USER" <(ls -oad "$1/$file" | cut -d " " -f3); then
			echo "$1/$file"
		fi
	done
}

for d in $DIRS; do
	if [ -d "$d" ]; then
		ls_user_files "$d"
	fi
done

exit 0
