#!/bin/bash

if (($# == 0))
then
	echo "usage: $0 f1 ... fn"
	exit
fi

while (($# > 0))
do
	suffix=$(ext $1)
	prefix=$(basename $1 $suffix)
	folder=$(dirname $1)
	mptopdf $1 1>&2
	mv "$folder/$prefix-0.pdf" "$folder/$prefix.pdf"
	rm $prefix.0 $prefix.log
	shift
done
