#!/bin/bash
#
# pdfcat -o <outputfile> fin1 fin2 ... 
# 
# Concatenate pdf files into a single file with gs
# 
# =================================================
# Author: Michael B Hynes, mbhynes@uwaterloo.ca
# License: GPL 3
# Creation Date: Fri Feb  6 14:07:35 2015
# Last Modified: Tue 24 Feb 2015 11:59:49 AM EST
# =================================================

SCRIPT_NAME=$(basename $0)
msg () {
	echo "$SCRIPT_NAME: $@" 1>&2
}
warn () {
	msg WARNING: $@
}
error () {
	msg ERROR: $@
}

fout=""
optstring="o:"
while getopts "$optstring" opt; do
	case "$opt" in
		o)
			fout="$OPTARG" 
			;;
		:)
			error "-$opt requires argument" 
			;; 
		?)
			error invalid option
			;; 
	esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
	disp_opts -h -n 6 $0 2>/dev/null
	exit 1
fi
if [ -z "$fout" ]; then
	error "-o <fout> must be specified"
	disp_opts -h -n 6 $SCRIPT_NAME 2>/dev/null
	exit 1
fi

msg "Compiling: $(tr ' ' '\n' <<< " $@ ") to $fout"
gs -dBATCH -q -dNOPAUSE -sDEVICE=pdfwrite -sOutputFile="$fout" "$@"

exit $?
