#!/bin/bash
# proper_noun
# 
# Convert stdin strings into Proper Nouns;
#
# Example:
# $ proper_noun <<< "de doop ba woop"
#	De Doop Ba Woop
#
# Note: this is a slow and stupid implementation. But it
# works. Internally, it uses a sed script written to a
# tempfile.
# =================================================
# Author: Michael B Hynes, mbhynes@uwaterloo.ca
# License: GPL 3
# Creation Date: Fri Feb  6 14:15:15 2015
# Last Modified: Fri Feb  6 14:18:53 2015
# =================================================

to_lower() {
	tr 'A-Z' 'a-z' 
}

make_sed_script()
{
	for c in {a..z}
	do
		C=$(tr 'a-z' 'A-Z' <<< $c)
		echo "s/\<$c([[:alpha:]\-_]*)\>/$C\1/g" 
	done
}

tmpscript=$(mktemp)
make_sed_script > $tmpscript 

while read line; do
	to_lower <<< $line \
		| sed -r -f $tmpscript
done 

rm $tmpscript
